site_name: Mariapedia
site_description: La respuesta de todas las preguntas estan aqui.
site_author: iortiz

# Copyright
copyright: Copyright &copy; 2023 Mariapedia

site_url: https://mariapedia.com

# Navigation
nav:
  - Home: 
    - index.md


# Extras
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DIPCehu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/donostia-international-physics-center-dipc


# Configuration
theme:
  name: material
  features:
    - navigation.indexes
  logo: images/mariapedia_logo-bco.png
  favicon: images/favicon.ico
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extra CSS styles
extra_css:
  - stylesheets/extra.css
  - stylesheets/dark-palette.css

# Extensions
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets


# Plugins
plugins:
  - search
  - minify:
      minify_html: true
